Create SortCommand feature v2
AY2425S1-CS2103T-F15-3/tp pull request #137
Opened 2024-10-28 16:56 UTC by BuffWuff1712

fixes #133.

created an internal ID for each Person to keep track of the order in which each Person Object is created. List command would also sort each Person according to their internal ID, while Sort command would sort each Person by their full name.

only possible flaw with this is that the internal ID is immutable. For eg if I add Person A, B, C and D (with IDs 1,2,3,4 respectively), and I remove Person B, Persons C and D will still have IDs 3 and 4 instead of being updated to 2 and 3.

Sorting will temper with the actual addressbook, as tempering with the UI display only will cause some issue when commands like Show are used right after Sort

2024-10-29 05:31 UTC, tayxuenye approved these changes
Reviewed and tested. Would suggest explaining sort more in-depth in helpWindow (see comment).

2024-10-29 05:31 UTC, tayxuenye commented on src/main/java/seedu/address/ui/HelpWindow.java
> +            + HELP_SORT_COMMAND
Should probably state that sort is permanent and it sorts by alphabetical order and to unsort, use list command.

2024-10-29 05:53 UTC, Vatinius requested changes
Don't have the time to test it fully yet, but I caught the same bug whereby it favoured capitalised names first again. Will test it more later when I have time.

![image](https://github.com/user-attachments/assets/b68b22e4-aaef-46c2-b6bb-980f256d8378)

2024-10-29 09:46 UTC, Tkaixiang commented
> Don't have the time to test it fully yet, but I caught the same bug whereby it favoured capitalised names first again. Will test it more later when I have time.
> 
> ![image](https://private-user-images.githubusercontent.com/45896928/380995355-b68b22e4-aaef-46c2-b6bb-980f256d8378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTU0NDIsIm5iZiI6MTczMDE5NTE0MiwicGF0aCI6Ii80NTg5NjkyOC8zODA5OTUzNTUtYjY4YjIyZTQtYWFlZi00NmMyLWI2YmItOTgwZjI1NmQ4Mzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA5NDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZGM1NDM3MWZiZjcxYzE3YWFmYWRlYTJjMjlmOGVkZDMxY2RiNGU5NWNkOTg3YWI1YTcyM2I2Mjg2ZjUwODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sBAjMNg1XDesODyWRecooNB6vqN0y-jydyO5-LGBq3E)

I think this is because capital letters are earlier on the ASCII table. I think we can consider a case insensitive sort instead and just dont mind if capital comes first or not since users probably wont prioritise that.

2024-11-01 01:10 UTC, Vatinius reviewed
Noticed that when i'm in "sorted" view and add a new contact, they are placed at the bottom of the list rather than in the alphabetical order like in previous iterations

2024-11-01 01:11 UTC, Vatinius approved these changes
I shall pre-approve first to enable a smoother process to merge in the event i'm not available to approve it later on.

2024-11-01 07:41 UTC, merged