Edit Add Command
AY2425S1-CS2103T-F15-3/tp pull request #60
Opened 2024-10-10 17:59 UTC by BuffWuff1712

Fixes #58

2024-10-11 07:41 UTC, Vatinius reviewed
Is changing the error message for the Add command intended as well?

The add error message still does not show that email onwards is optional
![image](https://github.com/user-attachments/assets/e8020fd7-4068-49db-8014-9064597edf8c)

2024-10-12 05:46 UTC, Vatinius requested changes
Set my review to "Request changes"

2024-10-12 05:51 UTC, Vatinius reviewed
Need to make mental note if we want to stick with this formatting/styling of the empty email, address and tags field or not when we add individuals without filling up all the fields.

![image](https://github.com/user-attachments/assets/fdb84735-9531-4845-9229-572e36c13626)
![image](https://github.com/user-attachments/assets/ae80f298-01bd-4407-985f-8fdc6a304055)

2024-10-12 14:25 UTC, BuffWuff1712 commented
Made changes to formatting of error and success messages for add command

2024-10-13 09:33 UTC, Tkaixiang approved these changes
tested - lgtm

2024-10-14 01:01 UTC, Vatinius approved these changes
lgtm!

2024-10-14 01:02 UTC, merged

2024-10-14 05:12 UTC, sayomaki reviewed
I have looked through the code (despite it being merged), some comments (for future updates)

2024-10-14 05:12 UTC, sayomaki commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        if (trimmedEmail.isEmpty()) {
Ditto here.

2024-10-14 05:12 UTC, sayomaki commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        if (trimmedAddress.isEmpty()) {
Do we need the check here? Since `Address.isValidAddress` has already been updated.

2024-10-14 08:42 UTC, sayomaki commented on src/test/java/seedu/address/model/person/AddressTest.java
> -        assertFalse(Address.isValidAddress(" ")); // spaces only
Maybe for this we can instead keep the test cases and just change the assertion from false to true?